### ISSUE TITLE
java.nio.file.FileSystemLoopException is raised when MaterialRepsitory#scan() is invoked on a network drive located on Google Driver Stream

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/ScreenshotSupportForKatalonStudio#2]
2019-05-20 10:38:39.762 ERROR c.k.k.core.context.internal.TestHooker   - ❌ org.codehaus.groovy.runtime.InvokerInvocationException: java.nio.file.FileSystemLoopException: G:\マイドライブ\vtprojects\CorporateQuickVT\Materials\

**Comment by kazurayam** [comment]
Oracle's Java [Tutorial document](https://docs.oracle.com/javase/tutorial/essential/io/walk.html#order) discusses about FileSystemLoopException.

>You need to decide whether you want symbolic links to be followed. If you are deleting files, for example, following symbolic links might not be advisable. If you are copying a file tree, you might want to allow it. By default, walkFileTree does not follow symbolic links.

>The visitFile method is invoked for files. If you have specified the FOLLOW_LINKS option and your file tree has a circular link to a parent directory, the looping directory is reported in the visitFileFailed method with the FileSystemLoopException. The following code snippet shows how to catch a circular link and is from the Copy example:
```
@Override
public FileVisitResult
    visitFileFailed(Path file,
        IOException exc) {
    if (exc instanceof FileSystemLoopException) {
        System.err.println("cycle detected: " + file);
    } else {
        System.err.format("Unable to copy:" + " %s: %s%n", file, exc);
    }
    return CONTINUE;
}
```
>This case can occur only when the program is following symbolic links.

**Comment by kazurayam** [comment]
I would do 2 changes to the Materials library.
1.  implemen the visitFileFailed() method to cach FileSystemLoopException. Do not throw the FileSystemLoopException to the top level.
2. I do not want to FOLLOW_LINKS

**Comment by kazurayam** [comment]
see the line#189 of https://github.com/kazurayam/Materials/blob/0.70.2/src/main/groovy/com/kazurayam/materials/repository/RepositoryFileVisitor.groovy

This class does NOT implement visitFileFailed() method.
Therefore when a looping directory found, an FileSystemLoopException is raised to the top level and therefore the process will be terminated.

Now I understand that I need to change 
`com.kazurayam.materials.repository.RepositoryFileVisitor` class so that it implements the visitFileFailed() method and mangle the Exception by reporting it to the Log.

**Comment by kazurayam** [comment]
com.kazurayam.materials.Helpers class has problem as well.
```
2019-05-20 11:45:11.417 INFO  c.k.katalon.core.main.TestSuiteExecutor  - START Test Suites/VT/cleanMaterials
2019-05-20 11:45:11.474 INFO  c.k.katalon.core.main.TestSuiteExecutor  - hostName = qcq0264 - N19-D267.quick.local
2019-05-20 11:45:11.475 INFO  c.k.katalon.core.main.TestSuiteExecutor  - os = Windows 10 64bit
2019-05-20 11:45:11.475 INFO  c.k.katalon.core.main.TestSuiteExecutor  - hostAddress = 172.19.71.132
2019-05-20 11:45:11.477 INFO  c.k.katalon.core.main.TestSuiteExecutor  - katalonVersion = 6.1.5.3
2019-05-20 11:45:11.808 INFO  c.k.k.c.keyword.builtin.CommentKeyword   - VTListener#beforeTestSuite() was invoked
[RepositoryFileVisitor#visitFileFailed] circular link was detected: G:\マイドライブ\vtprojects\CorporateQuickVT\Materials\_, which will be ignored
[RepositoryFileVisitor#visitFileFailed] circular link was detected: G:\マイドライブ\vtprojects\CorporateQuickVT\Storage\_, which will be ignored
2019-05-20 11:45:12.697 INFO  c.k.katalon.core.main.TestCaseExecutor   - --------------------
2019-05-20 11:45:12.697 INFO  c.k.katalon.core.main.TestCaseExecutor   - START Test Cases/VT/cleanMaterials
2019-05-20 11:45:12.736 INFO  c.k.k.c.keyword.builtin.CommentKeyword   - VTListener#beforeTestCase() was invoked
2019-05-20 11:45:12.769 INFO  c.k.k.c.keyword.builtin.CommentKeyword   - VisualTestingListenerImpl#beforeTestCase CURRENT_TESTSUITE_ID is "Test Suites/VT/cleanMaterials"
2019-05-20 11:45:12.772 INFO  c.k.k.c.keyword.builtin.CommentKeyword   - VisualTestingListenerImpl#beforeTestCase CURRENT_TESTSUITE_TIMESTAMP is "20190520_114505"
2019-05-20 11:45:12.775 INFO  c.k.k.c.keyword.builtin.CommentKeyword   - VisualTestingListenerImpl#beforeTestCase CURRENT_TESTCASE_ID is "Test Cases/VT/cleanMaterials"
2019-05-20 11:45:12.798 INFO  c.k.k.c.keyword.builtin.CommentKeyword   - VisualTestingListenerImpl#beforeTestCase MATERIAL_REPOSITORY is "{"MaterialRepository":{"baseDir":"G:\\\u30DE\u30A4\u30C9\u30E9\u30A4\u30D6\\vtprojects\\CorporateQuickVT\\Materials","currentTsName":{"id": "Test Suites/VT/cleanMaterials","abbreviatedId": "VT/cleanMaterials","value": "VT.cleanMaterials"},"currentTsTimestamp":{"TSuiteTimestamp":{"timestamp":"20190520_114505"}},"repoRoot":{"RepositoryRoot":{"tSuiteResults":[{"TSuiteResult":{"tSuiteName":{"id": "Test Suites/VT/cleanMaterials","abbreviatedId": "VT/cleanMaterials","value": "VT.cleanMaterials"},"tSuiteTimestamp": "20190520_114505","tSuiteTimestampDir": "G:\\\u30DE\u30A4\u30C9\u30E9\u30A4\u30D6\\vtprojects\\CorporateQuickVT\\Materials\\VT.cleanMaterials\\20190520_114505","lastModified":"-999999999-01-01T00:00","length":0,"tCaseResults": []}},{"TSuiteResult":{"tSuiteName":{"id": "_","abbreviatedId": "_","value": "_"},"tSuiteTimestamp": "_","tSuiteTimestampDir": "G:\\\u30DE\u30A4\u30C9\u30E9\u30A4\u30D6\\vtprojects\\CorporateQuickVT\\Materials\\_\\_","lastModified":"-999999999-01-01T00:00","length":0,"tCaseResults": []}}],"baseDir":"G:\\\u30DE\u30A4\u30C9\u30E9\u30A4\u30D6\\vtprojects\\CorporateQuickVT\\Materials","reportsDir":"G:\\\u30DE\u30A4\u30C9\u30E9\u30A4\u30D6\\vtprojects\\CorporateQuickVT\\Materials\\..\\Reports",}}}}"
2019-05-20 11:45:12.805 INFO  c.k.k.c.keyword.builtin.CommentKeyword   - VisualTestingListenerImpl#beforeTestCase MATERIAL_STORAGE is "{"MaterialStorage":{"baseDir":"G:\\\u30DE\u30A4\u30C9\u30E9\u30A4\u30D6\\vtprojects\\CorporateQuickVT\\Storage"}}"
2019-05-20 11:45:12.863 DEBUG testcase.cleanMaterials                  - 1: mr = internal.GlobalVariable[MATERIAL_REPOSITORY.getName()]
2019-05-20 11:45:12.864 DEBUG testcase.cleanMaterials                  - 2: assert mr != null
2019-05-20 11:45:12.866 DEBUG testcase.cleanMaterials                  - 3: Helpers.deleteDirectoryContents(mr.getBaseDir())
2019-05-20 11:45:12.914 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/VT/cleanMaterials FAILED.
Reason:
java.nio.file.FileSystemLoopException: G:\マイドライブ\vtprojects\CorporateQuickVT\Materials\_\_
	at java_nio_file_Files$walkFileTree.call(Unknown Source)
	at com.kazurayam.materials.Helpers.deleteDirectory(Helpers.groovy:90)
...
```

**Comment by kazurayam** [comment]
I need fix Helpers#copyDirectory() method as well.
```
2019-05-20 13:10:05.660 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/VT/backupCurrentTSuiteResult FAILED.
Reason:
java.nio.file.FileSystemLoopException: G:\マイドライブ\vtprojects\CorporateQuickVT\Materials\CorporateQuick.chronos_capture\20190520_130911\CorporateQuick.JPN.topPageTest
	at java_nio_file_Files$walkFileTree.call(Unknown Source)
	at com.kazurayam.materials.Helpers.copyDirectory(Helpers.groovy:225)
```
