### ISSUE TITLE
MaterialDescription class must emit JSON text which is properly escaped

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/ScreenshotSupportForKatalonStudio#49]
https://github.com/kazurayam/Materials/blob/0.80.0/src/main/groovy/com/kazurayam/materials/MaterialDescription.groovy toJsonText() is as follows:

```
String toJsonText() {
        StringBuilder sb = new StringBuilder()
        sb.append("{")
        sb.append('"category":"')
        sb.append(this.getCategory())
        sb.append('",')
        sb.append('"description":"')
        sb.append(this.getDescription())
        sb.append('"')
        sb.append("}")
        return sb.toString()
    }
```

This implementation is bad. Strings in JSON must be escaped.

Use `escapeAsJsonText()` of https://github.com/kazurayam/Materials/blob/0.80.0/src/main/groovy/com/kazurayam/materials/Helpers.groovy

**Comment by kazurayam** [comment]
we can reproduce the problem with
https://github.com/kazurayam/Materials/commit/d9373080e4e6b075f1e04e2733d0d8c96aaecaac

run MaterialRepositoryImplSpec # test_resolveScreenshotPathByURLPathComponents_writes_MaterialDescription_in_MaterialMetadataBundle()

You will see the following error
```

Unable to determine the current character, it is not a string, number, array, or object

The current character read is [SPACE] with an int value of 32
Unable to determine the current character, it is not a string, number, array, or object
line number 9
index number 351
                    "description": 
..................................^
groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is [SPACE] with an int value of 32
Unable to determine the current character, it is not a string, number, array, or object
line number 9
index number 351
                    "description": 
..................................^
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:202)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeJsonObject(JsonParserCharArray.java:128)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:182)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeJsonObject(JsonParserCharArray.java:128)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:182)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeJsonObject(JsonParserCharArray.java:128)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:182)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeJsonArray(JsonParserCharArray.java:322)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:178)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeJsonObject(JsonParserCharArray.java:128)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:182)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValue(JsonParserCharArray.java:153)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeFromChars(JsonParserCharArray.java:43)
	at org.apache.groovy.json.internal.JsonParserCharArray.parse(JsonParserCharArray.java:380)
	at org.apache.groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:110)
	at groovy.json.JsonSlurper.parseText(JsonSlurper.java:202)
	at com.kazurayam.materials.metadata.MaterialMetadataBundle.deserialize(MaterialMetadataBundle.groovy:44)
	at com.kazurayam.materials.metadata.MaterialMetadataBundle.deserialize(MaterialMetadataBundle.groovy:37)
	at com.kazurayam.materials.MaterialRepositorySpec.test_resolveScreenshotPathByURLPathComponents_writes_MaterialDescription_in_MaterialMetadataBundle(MaterialRepositorySpec.groovy:322)

com.kazurayam.materials.MaterialRepositorySpec > test_resolveScreenshotPathByURLPathComponents_writes_MaterialDescription_in_MaterialMetadataBundle FAILED
    groovy.json.JsonException at MaterialRepositorySpec.groovy:322
1 test completed, 1 failed
```
