### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke method getTCaseResultList() on null object

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/ScreenshotSupportForKatalonStudio#5]
https://forum.katalon.com/t/cannot-invoke-method-gettcaseresultlist-on-null-object/37890

```
Hi @kazurayam, sorry for the directly mention.
We’re using your Visualtesting with katalon (thank you for your great works!!)… and we are facing a trouble.

My tests are passed in Mac OS but it fails in Windows. (we want to use it in azure DevOps, it fails both in DevOps and virtual Windows env.)

What are the possible reasons?
I think it fails when getting the location of “Storage” (and “Report”) folder… but they are exist at the same project.

I’m a beginner for automation, so please let me know if you need more information.

2019-12-24 06:38:38.882 INFO  com.kms.katalon.core.util.KeywordUtil    - VisualTestingListenerImpl#beforeTestSuite testSuiteTimestamp=20191224_063826
2019-12-24 06:38:38.977 ERROR c.k.k.core.context.internal.TestHooker   - ❌ java.lang.NullPointerException: Cannot invoke method getTCaseResultList() on null object
	at com.kazurayam.materials.impl.TSuiteResultImpl$getTCaseResultList$5.call(Unknown Source)
	at com.kazurayam.materials.repository.RepositoryFileVisitor.resolveLastModifiedOfTSuiteResult(RepositoryFileVisitor.groovy:233)
	at com.kazurayam.materials.repository.RepositoryFileVisitor.postVisitDirectory(RepositoryFileVisitor.groovy:136)
	at com.kazurayam.materials.repository.RepositoryFileVisitor.postVisitDirectory(RepositoryFileVisitor.groovy)
	at java_nio_file_Files$walkFileTree.call(Unknown Source)
	at com.kazurayam.materials.repository.RepositoryFileScanner.scan(RepositoryFileScanner.groovy:109)
	at com.kazurayam.materials.repository.RepositoryFileScanner$scan.call(Unknown Source)
	at com.kazurayam.materials.impl.MaterialRepositoryImpl.scan(MaterialRepositoryImpl.groovy:95)
	at com.kazurayam.materials.impl.MaterialRepositoryImpl.<init>(MaterialRepositoryImpl.groovy:78)
	at com.kazurayam.materials.impl.MaterialRepositoryImpl.newInstance(MaterialRepositoryImpl.groovy:88)
	at com.kazurayam.materials.impl.MaterialRepositoryImpl$newInstance.call(Unknown Source)
	at com.kazurayam.materials.MaterialRepositoryFactory.createInstance(MaterialRepositoryFactory.groovy:33)
	at com.kazurayam.materials.MaterialRepositoryFactory$createInstance.call(Unknown Source)
	at com.kazurayam.materials.impl.MaterialStorageImpl.<init>(MaterialStorageImpl.groovy:45)
	at com.kazurayam.materials.impl.MaterialStorageImpl.newInstance(MaterialStorageImpl.groovy:55)
	at com.kazurayam.materials.impl.MaterialStorageImpl$newInstance.call(Unknown Source)
	at com.kazurayam.materials.MaterialStorageFactory.createInstance(MaterialStorageFactory.groovy:19)
	at com.kazurayam.materials.MaterialStorageFactory$createInstance.call(Unknown Source)
	at com.kazurayam.visualtesting.VisualTestingListenerImpl.beforeTestSuite(VisualTestingListenerImpl.groovy:160)
	at com.kazurayam.visualtesting.VisualTestingListenerImpl$beforeTestSuite.call(Unknown Source)
	at VTListener.beforeTestSuite(VTListener.groovy:19)
	at VTListener.invokeMethod(VTListener.groovy)
	at com.kms.katalon.core.context.internal.TestHooker.invokeMethod(TestHooker.java:111)
	at com.kms.katalon.core.context.internal.TestHooker.lambda$3(TestHooker.java:95)
	at com.kms.katalon.core.context.internal.TestHooker.invokeContextMethods(TestHook
```

**Comment by kazurayam** [comment]
See

https://forum.katalon.com/t/cannot-invoke-method-gettcaseresultlist-on-null-object/37890/8

She created some folders/files under the Storage directory. These unexpected folders/files made the RepositoryScanner crazy. That was the cause of NPE.

**Comment by kazurayam** [comment]
RepostiroyScanner should be more robust. It should not throw NPE even when it finds unexpected files/folders in the Storage directory.

**Comment by kazurayam** [comment]
start working on this

**Comment by kazurayam** [comment]
NPE is not throw any longer.
